Add CosWriter
easee/Cos pull request #6
Opened 2022-04-07 21:35 UTC by JanErikFoss

Adds a CosWriter for turning a list of observations into a COS package

2022-04-11 08:45 UTC, hbjorgo requested changes

2022-04-11 08:45 UTC, hbjorgo commented on src/Cos/CosWriter.cs
> +                    writer?.WriteByte((byte)(o.Value ? 1 : 0));
Either assume that writer is not null or check it in he beginning of the method: if (writer == null) throw new ArgumentNullException(nameof(writer));

If checking for null in the beginning of the method, also do it in "SerializeCOSVersion1" method.

2022-04-11 08:45 UTC, hbjorgo commented on src/Cos/CosWriter.cs
> +        public string SerializeB64(List<Observation> observations, byte version = 1, byte cosHeaderFlags = (byte)COSHeaderFlag.COS_HEADER_64BIT_TIMESTAMPS)
I don't see the need for this method - all it does is convert the result, and the caller can easily do this. Cos is not dependent on Base64. But if we want to keep it - rename to "SerializeToBase64" to make it more explicit.

2022-04-11 08:45 UTC, hbjorgo commented on src/Cos/Observation.cs
> +        public virtual int CompareTo(Observation other) => throw new NotImplementedException();
We either need to implement CompareTo in the base class, or remove IComparable from it and add it to the sub classes. If implemented in the base class, the ID and timestamp could be compared, but I'm not sure if it would make sense and be easily understood by callers...

2022-04-11 08:45 UTC, hbjorgo commented on src/Tests/Cos.Tests/CosWriterTests.cs
> +    public class CosWriterTests
Add tests for unsupported cos version and invalid header byte.

2022-04-11 14:00 UTC, JanErikFoss commented on src/Cos/CosWriter.cs
> +                    writer?.WriteByte((byte)(o.Value ? 1 : 0));
Good catch, I forgot this when I split up the existing function that both returned the observation type and wrote to the writer.

2022-04-11 14:11 UTC, JanErikFoss commented on src/Cos/Observation.cs
> +        public virtual int CompareTo(Observation other) => throw new NotImplementedException();
I don't see why we have to implement it in the abstract base class. And removing IComparable from the base class doesn't allow comparing Observation without casting to Observation<TValue> first.

2022-04-13 05:45 UTC, hbjorgo approved these changes

2022-04-13 16:45 UTC, merged